### ISSUE TITLE
How do you start up the server[question]

### ISSUE THREAD

**Issue by reteps** [unixpickle/safeval.pw#2]
I am thinking of creating an API, and how to start it up. Do you have it startup on login? A background process for the server?

**Comment by reteps** [comment]
*A background process for the api I meant

**Comment by unixpickle** [comment]
In order to use this, you need to have an instance of Chrome/Chromium running in the background. You also need to run the server process itself. You will likely need a dedicated host for this, or at least a VPS.

If you want to run Chrome on a headless server, I suggest using Docker. With Docker installed, you can run the following:

```
docker run \
  -p 9222:9222 \
  --rm \
  --entrypoint /chrome-linux/chrome \
  unixpickle/muniverse:0.59.0 \
  --headless \
  --mute-audio \
  --no-sandbox \
  --remote-debugging-port=9222 \
  --remote-debugging-address=0.0.0.0 \
  --disable-gpu \
  --disable-webgl
```

Right now, I run both the safeval server itself and a Docker container in a `tmux` session. It's actually running on a computer at my house which wasn't doing anything else. This is obviously not a permanent solution; I am planning to put a more permanent challenge solution into kahoot-hack once it's clear that Kahoot has stopped changing their challenges.
